start:
    bash ../lib/start.sh

stop:
    bash ../lib/stop.sh

reset:
    bash ../lib/reset.sh

create-viper-api-key:
    bash ../lib/create-viper-api-key.sh

evaluate:
    bash init/evaluate.sh

seed:
    bash init/seed.sh

integrate:
    bash init/integrate.sh

test:
    just create-viper-api-key
    just seed
    just evaluate
    just integrate
    just evaluate
